### ISSUE TITLE
The wallet does not exist.  Run with the --create option to initialize and create it.

### ISSUE THREAD

**Issue by nisang** [hybridnetwork/hxwallet#7]
First step Run:
## **hxwallet -u user -P pass --create**
show success：The wallet has been created successfully.

Second step Run:
## **hxwallet -u user -P pass --testnet**
[WRN] HXW: open /root/.hxwallet/hxwallet.conf: no such file or directory
The wallet does not exist.  Run with the --create option to initialize and create it.

System is Debian ,golang version is "go1.10 linux/amd64",System use docker .

**Comment by nisang** [comment]
desc:**https://dev.aliyun.com/detail.html?spm=5176.1972343.2.10.77ad5aaawMQsPE&repoId=127337**

docker image link : **docker pull registry.cn-hangzhou.aliyuncs.com/nisang/hcash:0.1.0**

**Comment by nisang** [comment]
in my debian system ,"/root/.hxwallet/mainnet" hava "wallet.db" file, why run "hxwallet -u user -P pass --testnet" cannot success,still show "The wallet does not exist.  Run with the --create option to initialize and create it.".....

**Comment by bogrod** [comment]
This is because you have to run 
```
$ hxwallet --testnet --create
```
with the testnet flag to specify creating a wallet on the testnet. Without this flag a mainnet wallet will be created and is unusable for testnet.
