### ISSUE TITLE
http://faucet1.hybrid.network 无法访问

### ISSUE THREAD

**Issue by heaoven** [hybridnetwork/hxwallet#9]
http://faucet1.hybrid.network 无法访问

**Comment by nisang** [comment]
* faucet1  [http://faucet1.testnet.hybrid.network/](http://faucet1.testnet.hybrid.network/ "http://faucet1.testnet.hybrid.network/") 

* faucet2  [http://faucet2.testnet.hybrid.network](http://faucet2.testnet.hybrid.network "http://faucet2.testnet.hybrid.network") 
* 
* explorer  [http://explorer1.testnet.hybrid.network](http://explorer1.testnet.hybrid.network "http://explorer1.testnet.hybrid.network")
* pool  [http://stakepool1.testnet.hybrid.network/](http://stakepool1.testnet.hybrid.network/ "http://stakepool1.testnet.hybrid.network/")

add testnet to link

**Comment by heaoven** [comment]
Tanks . It's done.
